### PR TITLE
Fixes css issue and adds new flags

### PR DESCRIPTION
**Pull request by aeisenberg**
This PR fixes an incorrect css directive for the Costa Rican flag. It also adds Kosovo and an "International" flag. 

See: https://commons.wikimedia.org/wiki/File%3AInternational_Flag_of_Planet_Earth.svg

### CODE REVIEW

**Comment by aeisenberg** [comment]
Hi, I'd rather not fork this. So, please let me know what I should do to get this all merged.

**Comment by maxlibin** [comment]
Lgtm, quick question why do you to delete the optimized files?

**Comment by aeisenberg** [comment]
Thanks for looking into this.

I deleted them only because I couldn't tell how they were being used and as
far as I could tell they are the same as the non-optimized files. If you
want them back, I can push up a new commit to restore them.

**Comment by maxlibin** [comment]
would be nice to keep the optmized folder, the optimized folder using svgo to reduce the svg file size.

**Comment by aeisenberg** [comment]
No problem. I added the optimized flags back.

**Comment by maxlibin** [comment]
Thanks

**Pull request merged**
