### PR TITLE
adding optimized flags

### PR DESCRIPTION
**Pull request by ritcheyer**
Ran the flags through SVGO similar to my PR here https://github.com/lipis/flag-icon-css/pull/393.

Efficiencies gained and added to a separate folder.

### CODE REVIEW

**Comment by sandstrom** [comment]
Great, but instead of keeping them in a separate optimized directory, wouldn't it make more sense to replace the old flags with new optimized ones?

**Comment by maxlibin** [comment]
@sandstrom 👍 make sense, will update.

**Comment by ritcheyer** [comment]
I can do that for you if you’d like.

**Comment by maxlibin** [comment]
@ritcheyer 💯 👍

**Comment by ritcheyer** [comment]
done https://github.com/maxlibin/lite-flag-icon-css/pull/2

**Pull request merged**
